# Generated by Django 5.2.10 on 2026-01-21 09:47

import django.contrib.auth.models
import django.db.models.deletion
import manage_users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_contact', models.CharField(blank=True, max_length=15, null=True, validators=[manage_users.models.validate_international_phone])),
                ('marital_status', models.CharField(choices=[('single', 'SINGLE'), ('married', 'MARRIED'), ('divorced', 'DIVORCED'), ('widowed', 'WIDOWED')], default='single', max_length=20)),
                ('christened', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profession_c', models.CharField(blank=True, choices=[('student', 'STUDENT'), ('computer_scientist', 'COMPUTER_SCIENTIST'), ('nurse', 'NURSE'), ('teacher', 'TEACHER'), ('engineer', 'ENGINEER'), ('doctor', 'DOCTOR'), ('lawyer', 'LAWYER'), ('other', 'OTHER')], max_length=100)),
                ('profession_o', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Censor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('general', 'GENERAL'), ('deputy', 'DEPUTY')], default='general', max_length=20)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_users.member')),
            ],
            options={
                'verbose_name': 'Censeur',
                'verbose_name_plural': 'Censeurs',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_users.profile'),
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('general', 'GENERAL'), ('deputy', 'DEPUTY')], default='general', max_length=20)),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_users.member')),
            ],
            options={
                'verbose_name': 'Secretaire',
                'verbose_name_plural': 'Secretaires',
            },
        ),
        migrations.CreateModel(
            name='Treasurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_users.member')),
            ],
            options={
                'verbose_name': 'Tresorier',
                'verbose_name_plural': 'Tresoriers',
            },
        ),
    ]
