# Generated by Django 5.2.10 on 2026-01-21 10:43

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manage_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperadminChorale',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Superadmin Chorale',
                'verbose_name_plural': 'Superadmins Chorale',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='censor',
            old_name='membre',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='secretary',
            old_name='membre',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='treasurer',
            old_name='membre',
            new_name='member',
        ),
        migrations.CreateModel(
            name='MemberContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_contributed', models.DateField(auto_now_add=True)),
                ('annual_amount_target', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_users.member')),
            ],
        ),
        migrations.CreateModel(
            name='Saction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sanctioned', models.DateField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('time_limit', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_users.member')),
            ],
        ),
    ]
