# Generated by Django 6.0.1 on 2026-01-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0002_superadminchorale_rename_membre_censor_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercontribution',
            name='annual_amount_target',
        ),
        migrations.AddField(
            model_name='membercontribution',
            name='contribution_ref',
            field=models.CharField(default='contibution mensuelle', max_length=100),
        ),
    ]
