# Generated by Django 6.0.1 on 2026-01-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0003_remove_membercontribution_annual_amount_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_users.profile'),
        ),
    ]
