# Generated by Django 6.0.1 on 2026-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manage_users', '0003_alter_otpcode_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='manage_user_email_5843f1_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='manage_user_usernam_8ade26_idx'),
        ),
    ]
