# Generated by GitHub Copilot adaptation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0004_customuser_manage_user_email_5843f1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chorale_role',
            field=models.CharField(choices=[
                ('member', 'Membre'),
                ('secretary', 'Secrétaire'),
                ('treasurer', 'Trésorier'),
                ('censor', 'Censeur'),
            ], default='member', max_length=20),
            preserve_default=False,
        ),
    ]
