# Generated by Django 6.0.1 on 2026-05-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0005_add_customuser_chorale_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chorale_role',
            field=models.CharField(choices=[('member', 'Membre'), ('secretary', 'Secrétaire'), ('treasurer', 'Trésorier'), ('censor', 'Censeur')], default='member', max_length=20),
        ),
    ]
