# Generated by Django 6.0.1 on 2026-05-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0006_alter_customuser_chorale_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membercontribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sanction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='user',
        ),
        migrations.RemoveField(
            model_name='treasurer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Censor',
        ),
        migrations.DeleteModel(
            name='MemberContribution',
        ),
        migrations.DeleteModel(
            name='Sanction',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
        migrations.DeleteModel(
            name='Treasurer',
        ),
    ]
