# Generated by Django 6.0.1 on 2026-05-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0007_remove_membercontribution_user_remove_sanction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chorale_role',
            field=models.CharField(choices=[('member', 'Member'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer'), ('censor', 'Censor')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('super_admin_chorale', 'Super Chorale Admin')], default='member', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession_c',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('computer_scientist', 'Computer scientist'), ('nurse', 'Nurse'), ('teacher', 'Teacher'), ('engineer', 'Engineer'), ('doctor', 'Doctor'), ('lawyer', 'Lawyer'), ('other', 'Other')], max_length=100),
        ),
    ]
