# Generated by Django 6.0.1 on 2026-04-01 03:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('established_date', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('type_c', models.CharField(choices=[('chorale', 'CHORALE'), ('mouvement', 'MOUVEMENT'), ('association', 'ASSOCIATION')], default='chorale', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='chorale_logos/')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('meeting_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_group', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='chorales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type_cash_flow', models.CharField(choices=[('entrée', 'ENTREE'), ('sortie', 'SORTIE')], default='entrée', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_chorale.chorale')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lead', models.CharField(blank=True, max_length=255, null=True)),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_chorale.chorale')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_contributed', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_chorale.chorale')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('agenda', models.TextField()),
                ('minutes', models.TextField()),
                ('attendees', models.TextField()),
                ('report', models.FileField(blank=True, null=True, upload_to='meeting_reports/')),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_chorale.chorale')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="Date et heure de l'événement")),
                ('event_type', models.CharField(choices=[('payment', 'Paiement effectué'), ('warning', 'sanction appliquée'), ('person_add', 'membre ajouté'), ('person_remove', 'membre retiré'), ('upload_file', 'rapport'), ('other', 'autre')], help_text="Type d'événement", max_length=50)),
                ('description', models.TextField(help_text="Description détaillée de l'événement")),
                ('short_description', models.CharField(blank=True, help_text='Description courte pour les notifications', max_length=255)),
                ('comment', models.TextField(blank=True, help_text="Commentaire additionnel (ex: raison d'une sanction, etc)")),
                ('object_id', models.PositiveBigIntegerField(blank=True, help_text="ID de l'objet concerné", null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données contextuelles (ancienne valeur, nouvelle valeur, etc)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur au moment de l'action", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent du navigateur/appareil')),
                ('is_important', models.BooleanField(default=False, help_text="Indique si l'événement est considéré comme important pour les notifications")),
                ('chorale', models.ForeignKey(help_text="Chorale Concernée par l'événement", on_delete=django.db.models.deletion.CASCADE, related_name='events', to='manage_chorale.chorale')),
                ('content_type', models.ForeignKey(blank=True, help_text="Type de l'objecct concerné (ex: Contribution, Sanction) ", null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur ayant déclanché l'événement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['chorale', '-timestamp'], name='manage_chor_chorale_e57a15_idx'), models.Index(fields=['user', '-timestamp'], name='manage_chor_user_id_18e907_idx'), models.Index(fields=['event_type'], name='manage_chor_event_t_02da2b_idx')],
            },
        ),
    ]
