# Generated by Django 5.2.10 on 2026-01-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_chorale', '0001_initial'),
        ('manage_users', '0002_superadminchorale_rename_membre_censor_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorale',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_users.superadminchorale'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='chorale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_chorale.chorale'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='chorale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_chorale.chorale'),
        ),
        migrations.AddField(
            model_name='meetingreport',
            name='chorale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_chorale.chorale'),
        ),
    ]
