# Generated by Django 6.0.1 on 2026-04-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chorale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chorale',
            name='slug',
        ),
    ]
