# Generated by Django 6.0.1 on 2026-04-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chorale', '0002_remove_chorale_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chorale',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
