# Generated by Django 6.0.1 on 2026-05-15 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chorale', '0003_chorale_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoraleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(choices=[('practice', 'Pratique'), ('meeting', 'Réunion'), ('concert', 'Concert'), ('other', 'Autre')], default='practice', max_length=20)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='event_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chorale_events', to='manage_chorale.chorale')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chorale_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['chorale', 'date'], name='manage_chor_chorale_04b369_idx'), models.Index(fields=['created_by', 'date'], name='manage_chor_created_b3bea5_idx')],
            },
        ),
    ]
