# Generated by Django 6.0.1 on 2026-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chorale', '0004_choraleevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='choraleevent',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dépenses (XAF)'),
        ),
        migrations.AddField(
            model_name='choraleevent',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Entrées (XAF)'),
        ),
        migrations.AlterField(
            model_name='choraleevent',
            name='event_type',
            field=models.CharField(choices=[('practice', 'Pratique'), ('meeting', 'Réunion'), ('concert', 'Concert'), ('assistance', 'Assistance'), ('other', 'Autre')], default='practice', max_length=20),
        ),
    ]
