# Generated by Django 6.0.1 on 2026-05-15 22:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chorale', '0005_choraleevent_expenses_choraleevent_income_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='date_contributed',
        ),
        migrations.AddField(
            model_name='cashflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashflow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flows_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='chorale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='manage_chorale.chorale'),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='type_cash_flow',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], default='entree', max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Montant attendu par membre', max_digits=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='chorale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='manage_chorale.chorale'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Objectif total chorale (optionnel)', max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['chorale', '-date'], name='manage_chor_chorale_da5826_idx'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('chorale', 'title'), name='uniq_contrib_per_chorale'),
        ),
        migrations.AddField(
            model_name='membercontribution',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='manage_chorale.contribution'),
        ),
        migrations.AddField(
            model_name='membercontribution',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membercontribution',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='membercontribution',
            index=models.Index(fields=['contribution', 'member'], name='manage_chor_contrib_e8777a_idx'),
        ),
        migrations.AddIndex(
            model_name='membercontribution',
            index=models.Index(fields=['member', '-paid_at'], name='manage_chor_member__32222e_idx'),
        ),
    ]
