# Generated by Django 6.0.1 on 2026-05-15 23:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chorale', '0006_membercontribution_alter_cashflow_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_justified', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='manage_chorale.choraleevent')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['member', '-recorded_at'], name='manage_chor_member__595313_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'member'), name='uniq_absence_per_event_member')],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanction_type', models.CharField(choices=[('warning', 'Avertissement'), ('fine', 'Amende'), ('suspension', 'Suspension')], default='warning', max_length=20)),
                ('reason', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Seulement pour les amendes', max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('time_limit', models.DateField(blank=True, help_text="Délai d'acquittement (amende) ou de levée (suspension)", null=True)),
                ('applied_at', models.DateField(default=django.utils.timezone.now)),
                ('lifted_at', models.DateField(blank=True, help_text='Date de levée — null = sanction active', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chorale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='manage_chorale.chorale')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at', '-created_at'],
                'indexes': [models.Index(fields=['chorale', '-applied_at'], name='manage_chor_chorale_3590c3_idx'), models.Index(fields=['member', '-applied_at'], name='manage_chor_member__b553ad_idx')],
            },
        ),
    ]
