# Generated by Django 6.0.1 on 2026-05-17 23:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manage_chorale', '0007_absence_sanction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='type_cash_flow',
            field=models.CharField(choices=[('entree', 'Income'), ('sortie', 'Expense')], default='entree', max_length=20),
        ),
        migrations.AlterField(
            model_name='chorale',
            name='type_c',
            field=models.CharField(choices=[('chorale', 'Chorale'), ('mouvement', 'Movement'), ('association', 'Association')], default='chorale', max_length=20),
        ),
        migrations.AlterField(
            model_name='choraleevent',
            name='event_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('meeting', 'Meeting'), ('concert', 'Concert'), ('assistance', 'Attendance'), ('other', 'Other')], default='practice', max_length=20),
        ),
        migrations.AlterField(
            model_name='choraleevent',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expenses (XAF)'),
        ),
        migrations.AlterField(
            model_name='choraleevent',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Income (XAF)'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount expected per member', max_digits=10),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total chorale target (optional)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='chorale',
            field=models.ForeignKey(help_text='Chorale concerned by the event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='manage_chorale.chorale'),
        ),
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.TextField(blank=True, help_text='Additional comment (e.g., reason for a sanction)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of the related object (e.g., Contribution, Sanction)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Detailed description of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('payment', 'Payment made'), ('warning', 'Sanction applied'), ('person_add', 'Member added'), ('person_remove', 'Member removed'), ('upload_file', 'Report'), ('other', 'Other')], help_text='Event type', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="User's IP address at the time of the action", null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Indicates whether the event is considered important for notifications'),
        ),
        migrations.AlterField(
            model_name='event',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Contextual data (old value, new value, etc.)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID of the related object', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.CharField(blank=True, help_text='Short description for notifications', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who triggered the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent of the browser/device'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only for fines', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='lifted_at',
            field=models.DateField(blank=True, help_text='Lift date — null = sanction active', null=True),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='sanction_type',
            field=models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('suspension', 'Suspension')], default='warning', max_length=20),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='time_limit',
            field=models.DateField(blank=True, help_text='Payment deadline (fine) or end date (suspension)', null=True),
        ),
    ]
