# Generated by Django 6.0.1 on 2026-09-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chorale', '0011_swap_members_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='uso',
            field=models.CharField(default='se', max_length=150),
        ),
    ]
