# Generated by Django 6.0.1 on 2026-09-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chorale', '0012_membership_uso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='uso',
        ),
    ]
